/* CREATE DATABASE anagrafe; */ 
CREATE TABLE anagrafe.comuni (
   COD_REGIONE TINYINT(2) UNSIGNED NOT NULL,
   DESC_REGIONE VARCHAR(255),
   COD_PROVINCIA TINYINT(2) UNSIGNED NOT NULL,
   DESC_PROVINCIA VARCHAR(255),
   COD_COMUNE SMALLINT(2) UNSIGNED NOT NULL,
   DESC_COMUNE  VARCHAR(255),
   SIGLA_PROVINCIA CHAR(2),
   ANNO_CENSIMENTO VARCHAR(255),
   POPOLAZIONE_CENSITA_TOT VARCHAR(255),
   MAGG_PROP VARCHAR(255),
   DESC_TEMPO_GESTIONE VARCHAR(255),
   DATA_TEMPO_ELETTORALE VARCHAR(255),
   DATA_BALLOTTAGGIO VARCHAR(255),
   CONSIGLIERI_SPETTANTI SMALLINT,
   ASSESSORI_ASSEGNATI SMALLINT,
   SIGLA_TITOLO_ACCADEMICO VARCHAR(255),
   COGNOME VARCHAR(255),
   NOME VARCHAR(255),
   SESSO VARCHAR(255),
   DATA_NASCITA VARCHAR(255),
   DESC_SEDE_NASCITA VARCHAR(255),
   SEQ_ORDINA VARCHAR(255),
   DESCRIZIONE_CARICA VARCHAR(255),
   DATA_NOMINA VARCHAR(255),
   DESC_PARTITO VARCHAR(255),
   TIPO_MOVIMENTAZIONE VARCHAR(255),
   COD_MOVIMENTAZIONE VARCHAR(255),
   DESCRIZIONE VARCHAR(255),
   DATA_MOVIMENTAZIONE VARCHAR(255),
   DATA_CESSAZIONE VARCHAR(255),
   TITOLO_DI_STUDIO VARCHAR(255),
   PROFESSIONE VARCHAR(255)
);


/*
SELECT COD_COMUNE, DESC_REGIONE,DESC_PROVINCIA,DESC_COMUNE, sum(IF(`SESSO`="F",1,0)) as FEMM,sum(IF(`SESSO`="M",1,0)) as MASC, count(*) as TOT FROM comuni 
GROUP BY COD_COMUNE,COD_REGIONE,COD_PROVINCIA
*/