/* 
   Comuni
*/ 
CREATE TABLE anagrafe.comuni (
   COD_REGIONE TINYINT(2) UNSIGNED NOT NULL,
   DESC_REGIONE VARCHAR(255),
   COD_PROVINCIA TINYINT(2) UNSIGNED NOT NULL,
   DESC_PROVINCIA VARCHAR(255),
   COD_COMUNE SMALLINT(2) UNSIGNED NOT NULL,
   DESC_COMUNE  VARCHAR(255),
   SIGLA_PROVINCIA CHAR(2),
   ANNO_CENSIMENTO VARCHAR(255),
   POPOLAZIONE_CENSITA_TOT VARCHAR(255),
   MAGG_PROP VARCHAR(255),
   DESC_TEMPO_GESTIONE VARCHAR(255),
   DATA_TEMPO_ELETTORALE VARCHAR(255),
   DATA_BALLOTTAGGIO VARCHAR(255),
   CONSIGLIERI_SPETTANTI SMALLINT,
   ASSESSORI_ASSEGNATI SMALLINT,
   SIGLA_TITOLO_ACCADEMICO VARCHAR(255),
   COGNOME VARCHAR(255),
   NOME VARCHAR(255),
   SESSO VARCHAR(255),
   DATA_NASCITA VARCHAR(255),
   DESC_SEDE_NASCITA VARCHAR(255),
   SEQ_ORDINA VARCHAR(255),
   DESCRIZIONE_CARICA VARCHAR(255),
   DATA_NOMINA VARCHAR(255),
   DESC_PARTITO VARCHAR(255),
   TIPO_MOVIMENTAZIONE VARCHAR(255),
   COD_MOVIMENTAZIONE VARCHAR(255),
   DESCRIZIONE VARCHAR(255),
   DATA_MOVIMENTAZIONE VARCHAR(255),
   DATA_CESSAZIONE VARCHAR(255),
   TITOLO_DI_STUDIO VARCHAR(255),
   PROFESSIONE VARCHAR(255)
);


/*
   Province
*/
DROP TABLE IF EXISTS anagrafe.province;
CREATE TABLE anagrafe.province (
   COD_REGIONE VARCHAR(125),
   DESC_REGIONE VARCHAR(125),
   COD_PROVINCIA VARCHAR(125),
   DESC_PROVINCIA VARCHAR(125),
   COD_COMUNE VARCHAR(125),
   DESC_COMUNE VARCHAR(125),
   SIGLA_PROVINCIA VARCHAR(125),
   DESC_TEMPO_GESTIONE VARCHAR(125),
   DATA_TEMPO_ELETTORALE VARCHAR(125),
   DATA_BALLOTTAGGIO VARCHAR(125),
   CONSIGLIERI_SPETTANTI VARCHAR(125),
   ASSESSORI_ASSEGNATI VARCHAR(125),
   SIGLA_TITOLO_ACCADEMICO VARCHAR(125),
   COGNOME VARCHAR(125),
   NOME VARCHAR(125),
   SESSO VARCHAR(125),
   DATA_NASCITA VARCHAR(125),
   DESC_SEDE_NASCITA VARCHAR(125),
   SEQ_ORDINA VARCHAR(125),
   DESCRIZIONE_CARICA VARCHAR(125),
   DATA_NOMINA VARCHAR(125),
   DESC_PARTITO VARCHAR(125),
   TIPO_MOVIMENTAZIONE VARCHAR(125),
   COD_MOVIMENTAZIONE VARCHAR(125),
   DESCRIZIONE VARCHAR(125),
   DATA_MOVIMENTAZIONE VARCHAR(125),
   DATA_CESSAZIONE VARCHAR(125),
   TITOLO_DI_STUDIO VARCHAR(125),
   PROFESSIONE VARCHAR(125)
);

/*
   Regioni
*/
DROP TABLE IF EXISTS anagrafe.regioni;
CREATE TABLE anagrafe.regioni (
   COD_REGIONE VARCHAR(125),
   DESC_REGIONE VARCHAR(125),
   COD_PROVINCIA VARCHAR(125),
   DESC_PROVINCIA VARCHAR(125),
   COD_COMUNE VARCHAR(125),
   DESC_COMUNE VARCHAR(125),
   SIGLA_PROVINCIA VARCHAR(125),
   ANNO_CENSIMENTO VARCHAR(125),
   POPOLAZIONE_CENSITA_TOT VARCHAR(125),
   MAGG_PROP VARCHAR(125),
   DESC_TEMPO_GESTIONE VARCHAR(125),
   DATA_TEMPO_ELETTORALE VARCHAR(125),
   DATA_BALLOTTAGGIO VARCHAR(125),
   CONSIGLIERI_SPETTANTI VARCHAR(125),
   ASSESSORI_ASSEGNATI VARCHAR(125),
   SIGLA_TITOLO_ACCADEMICO VARCHAR(125),
   COGNOME VARCHAR(125),
   NOME VARCHAR(125),
   SESSO VARCHAR(125),
   DATA_NASCITA VARCHAR(125),
   DESC_SEDE_NASCITA VARCHAR(125),
   SEQ_ORDINA VARCHAR(125),
   DESCRIZIONE_CARICA VARCHAR(125),
   DATA_NOMINA VARCHAR(125),
   DESC_PARTITO VARCHAR(125),
   TIPO_MOVIMENTAZIONE VARCHAR(125),
   COD_MOVIMENTAZIONE VARCHAR(125),
   DESCRIZIONE VARCHAR(125),
   DATA_MOVIMENTAZIONE VARCHAR(125),
   DATA_CESSAZIONE VARCHAR(125),
   TITOLO_DI_STUDIO VARCHAR(125),
   PROFESSIONE  VARCHAR(125)
);

